### ISSUE TITLE
[Test] Add unit tests

### ISSUE THREAD

**Issue by mimshins** [sonnat/sonnat-ui#17]
### Discussed in https://github.com/sonnat/sonnat-ui/discussions/16

<div type='discussions-op-text'>

<sup>Originally posted by **createdbymahmood** February 17, 2022</sup>
Hi, I was wondering if you want to write some unit tests and I'd like to help you with this.</div>

**Comment by mimshins** [comment]
@createdbymahmood
Please confirm it.

**Comment by createdbymahmood** [comment]
Confirmed.

**Comment by mimshins** [comment]
Closing the issue due to the project being archived.
