### ISSUE TITLE
[Dialog] component causing `ResizeObserver` error

### ISSUE THREAD

**Issue by narmkon** [sonnat/sonnat-ui#27]
**Describe the bug**
useResizeSensor in Dialog Component hasn't set to debounce mode and it's causing
`ResizeObserver loop limit exceeded` error.
it's also flooding sentry

**To Reproduce**
use Dialog and add this error handler to window

`window.onerror = function(message, url, lineNumber) {  
      //save error and send to server for example.
      console.log(message,url,lineNumber);
      return true;
    };`  

**Expected behavior**
useResizeSensor should be debounced

**Screenshots**

**Desktop (please complete the following information):**
 - OS: linux/fedora
 - Browser : chrome
 - Version 105

**Additional context**
use debounce mode please, like the other components :)

**Comment by mimshins** [comment]
Confirmed.
The next week's patch will fix it.

Thanks for your report.

**Comment by mimshins** [comment]
@narmkon 
I have released a patch. Upgrade to `v2.0.8`.
